##############################################
# Chatbot Service Configuration
##############################################

# System-wide settings
system:
  log_level: INFO
  request_id_header: X-Request-ID
  environment: development

# Security settings
security:
  api_keys:
    - name: default
      key: "${API_KEY}"
      roles:
        - user
    - name: admin
      key: "${ADMIN_API_KEY}"
      roles:
        - user
        - admin
  rate_limiting:
    enabled: true
    provider: local
    requests: 100
    period_seconds: 60

# Cache settings
cache:
  enabled: true
  provider: local
  default_ttl_seconds: 3600
  max_size: 10000
  cleanup_interval_seconds: 300

# Chatbot API settings
chatbot:
  port: 8001
  host: 0.0.0.0
  workers: 4
  retrieval:
    vector_store:
      type: faiss
      index_path: "./data/indices/faiss.index"
      metadata_path: "./data/indices/faiss_metadata.json"
      dimension: 768  # Match embedding model dimension from sentence_transformer
      index_method: "hnsw"
    top_k: 5
    similarity_threshold: 0.7
  reranking:
    enabled: true
    type: custom
    top_k: 3
    score_threshold: 0.5
    # Custom reranker weights
    keyword_weight: 0.3
    tfidf_weight: 0.4
    length_weight: 0.2
    position_weight: 0.1
    min_score_threshold: 0.0
  generation:
    # Using Groq as the provider
    provider: "groq"
    # Groq settings
    model_name: "meta-llama/llama-4-scout-17b-16e-instruct" 
    temperature: 0.2
    max_output_tokens: 1024
    top_p: 0.95
    templates_dir: config/prompts/chatbot
    template: rag_prompt.jinja2
  memory:
    # Memory type: "simple", "mem0", "langgraph", or "langgraph_checkpoint"
    type: langgraph_checkpoint
    # LangGraph memory settings
    store_type: in_memory  # "in_memory" or "postgres"
    embedding_dimensions: 768
    max_history: 20
    # PostgreSQL settings (only used if store_type is "postgres")
    postgres:
      connection_string: "postgresql://username:password@localhost:5432/langgraph_db"
      # For pgvector support, ensure the database has the pgvector extension
      # CREATE EXTENSION IF NOT EXISTS vector;
    # Legacy settings for simple memory
    max_messages: 20
    message_expiry_minutes: 60
    max_sessions: 1000

# Vision configuration
vision:
  provider: "groq"
  config:
    model_name: "meta-llama/llama-4-scout-17b-16e-instruct"

# Embedding configuration
embedding:
  provider: "sentence_transformer"
  config:
    model: "all-mpnet-base-v2"
    device: "cpu"
    normalize_embeddings: true
    batch_size: 32
