# RAG Chatbot Configuration
# Based on code analysis - all parameters verified from source code

# Chatbot Configuration
chatbot:
  # Generation Configuration
  generation:
    provider: "vertex"          # Options: "vertex", "anthropic_vertex", "openai", "azure_openai"
    config:
      model_name: "gemini-1.5-pro-002"  # Model name
      temperature: 0.7                   # Generation temperature (0.0-1.0)
      max_tokens: 2048                   # Maximum tokens in response
      prompt_template: "./templates/rag_prompt.jinja2"  # Path to Jinja2 template

  # Retrieval Configuration
  retrieval:
    # Vector Store Configuration (must match ingestion config)
    vector_store:
      provider: "pgvector"      # Options: "faiss", "pgvector", "chromadb"
      config:
        dimension: 768          # Must match embedding model dimension
        connection_string: "postgresql://rushabhsmacbook@localhost:5432/rag_vector_db"
        table_name: "document_embeddings"
        schema_name: "public"   # PostgreSQL schema name (default: 'public')
        index_method: "hnsw"    # Options: "ivfflat", "hnsw"
        metadata_path: "./data/pgvector_metadata.pkl"
    
    # Embedding Configuration (must match ingestion config)
    embedding:
      provider: "vertex_ai"     # Options: "vertex", "vertex_ai", "openai", "openai_universal", "azure_openai"
      config:
        model: "text-embedding-004"     # Must match ingestion embedding model
        batch_size: 100
    
    # Retrieval Parameters
    top_k: 10                   # Number of documents to retrieve
    similarity_threshold: 0.7   # Minimum similarity threshold

  # Reranking Configuration
  reranking:
    type: "custom"              # Options: "cross_encoder", "custom"
    config:
      top_k: 5                  # Number of documents after reranking
      boost_recent: true        # Boost recent documents
      boost_factor: 1.2         # Boost factor for recent documents

  # Memory Configuration
  memory:
    type: "advanced_langgraph_checkpoint"  # Options: "simple", "mem0", "langgraph", "langgraph_checkpoint"
    max_history: 10               # Maximum conversation history length
    store_type: "postgres"        # Options: "in_memory", "postgres"
    postgres:
      connection_string: "postgresql://rushabhsmacbook@localhost:5432/langgraph_memory_db"

  # Workflow Configuration
  workflow:
    use_retrieval: true         # Enable document retrieval
    use_reranking: true         # Enable document reranking
    use_memory: true            # Enable conversation memory
    max_retries: 3              # Maximum workflow retries
    timeout_seconds: 30         # Workflow timeout

# API Configuration
api:
  host: "0.0.0.0"               # API host
  port: 8001                    # API port (different from ingestion)
  cors_origins: ["*"]           # CORS allowed origins
  api_key_required: true        # Whether API key is required

# Cache Configuration
cache:
  enabled: true                 # Enable caching
  ttl_seconds: 3600            # Cache TTL in seconds
  max_size: 1000               # Maximum cache entries

# Logging Configuration
logging:
  level: "INFO"                 # Options: "DEBUG", "INFO", "WARNING", "ERROR"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Health Check Configuration
health_check:
  enabled: true                 # Enable health checks
  interval_seconds: 30          # Health check interval
  timeout_seconds: 10           # Health check timeout

# Authentication Health Monitoring
auth_monitoring:
  enabled: true                 # Enable auth monitoring
  log_health_status: true       # Log auth health status
  validate_on_startup: true     # Validate auth on startup

# Processing Configuration
processing:
  max_concurrent_requests: 10   # Maximum concurrent chat requests
  request_timeout_seconds: 60   # Request timeout
  retry_attempts: 3             # Number of retry attempts
  retry_delay_seconds: 1        # Delay between retries

# Chat History Configuration
chat_history:
  use_chat_history: false       # Enable cross-session chat history by default
  chat_history_days: 7          # Days to look back for chat history
  max_messages_per_session: 100 # Maximum messages per session
